name: Build and Deploy

on:
    schedule:
      - cron: '*/15 * * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build
        run: npm run build
            git config user.name lbdtw-bot
            git add -A
            git commit -m "[bot] Update Api LBDTw Database"
            git push origin main