name: Build LBDTw

on:
  schedule:
    - cron: '*/15 * * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.BLOG_TOKEN }}
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
      - name: Install dependencies
        run: npm install
      - name: Build Astro
        run: npm run build
      - name: Commit and Push
        run: |
          git config --global user.email "bustosluciano89@gmail.com"
          git config --global user.name "Luchito"
          git diff --quiet && git diff --staged --quiet || git commit -am "[bot] Update LBDTw Blog"
          git push origin master